#!/bin/bash

#########
# COLORS
#########

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[0;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
blue="\033[1;34m"                                           ##
nc="\e[0m"                                                  ## 

arch=`uname -m`

function os () {
cat /etc/os-release > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
OS=DEBIAN 
		BIN="/usr/bin"
		main="/usr/share/shark"			
	else
		OS=TERMUX
		BIN="${PREFIX}/bin"
main="${PREFIX}/share/shark"
fi
}

function git_clone() { 
[ -d "${main}" ] && rm -rf ${main} > /dev/null 2>&1
git clone https://github.com/just-hack/shark ${main}
}


function dependencies() {
for i in apache2 php jq curl wget; do
    if [ ! -f "${BIN}/${i}" ]; then
    if [ ${OS} != "DEBIAN" ]; then
    apt-get install ncurses-utils ${i} -y 
    else
    sudo apt-get install ${i} -y 
    fi
    fi
    done
}

### INSTALL SCRIPT WGET INSTEAD OF GIT CLONE

function setup_ngrok() {
if [ ! -f  "${BIN}/ngrok" ]; then
printf "${white} installing ngrok"
if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
			ngrok_url="https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip"
		elif [[ "$arch" == *'aarch64'* ]]; then
			ngrok_url="https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip"
		elif [[ "$arch" == *'x86_64'* ]]; then
			ngrok_url="https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip"
		else
			ngrok_url="https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip"
		fi
		wget ${ngrok_url} -O ngrok.zip
unzip ngrok.zip && rm -rf ngrok.zip && chmod +x ngrok && mv ngrok $BIN

fi
}

function final_touchup() {
for i in shark; do
chmod +x ${main}/${i}
mv ${main}/${i} ${BIN}
printf "${purple} simply run : shark \n ${nc}"
done
}

os
git_clone
dependencies
setup_ngrok
final_touchup

#####################################
#       DON'T TRY TO COPY 😂😂     #
#   JUST LEARNING KEEP SUPPORTING   #
#             THANKYOU              #
#####################################
