#!/bin/bash

#########
# COLORS
#########

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[0;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
blue="\033[1;34m"                                           ##
nc="\e[0m"                                                  ## 



function os () {
cat /etc/os-release > /dev/null 2>&1
if [ "$?" -eq "0" ]; then
OS=DEBIAN 
		BIN="/usr/bin"
		main="/usr/share/shark"			
	else
		OS=TERMUX
		BIN="${PREFIX}/bin"
main="${PREFIX}/share"
fi
}

function git_clone() { 
[ -d "${main}" ] && rm -rf ${main} > /dev/null 2>&1
git clone https://github.com/just-hack/shark ${main}
}


function dependencies() {
for i in apache2 php jq curl wget; do
    if [ ! -f "${BIN}/${i}" ]; then
    sudo apt-get install ${i} -y 
    fi
    done
}

### INSTALL SCRIPT WGET INSTEAD OF GIT CLONE
# check or do as per device arch for ngrok installation

function install_ngrok() {
if [ ! -f  "${BIN}/ngrok" ]; then
printf "${white} installing ngrok"
if [ $OS != "TERMUX" ]; then
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
else
wget https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip -O ngrok.zip
fi
unzip ngrok.zip && rm -rf ngrok.zip
fi
}

function setup_ngrok() {
printf "${green} Enter your ngrok authtoken :\n "
read authtoken
$authtoken >> /dev/null 2>&1 && chmod +x ngrok && mv ngrok $BIN
}

function final_touchup() {
for i in shark; do
sudo mv ${main}/${i} ${BIN}
# cp -R shark_logo ${BIN}
printf "${purple} simply run : shark \n ${nc}"
done
}

os
git_clone
dependencies
install_ngrok
setup_ngrok
final_touchup

#####################################
#       DON'T TRY TO COPY 😂😂     #
#   JUST LEARNING KEEP SUPPORTING   #
#             THANKYOU              #
#####################################
