#!/bin/bash

#########
# COLORS
#########

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[0;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
blue="\033[1;34m"                                           ##
nc="\e[0m"                                                  ## 


BIN="${PREFIX}/bin"
main="${PREFIX}/share"

function os () {
if [ -e $BIN/termux-info ]; then
		OS=TERMUX			
	else
		OS=DEBIAN 
		BIN="/usr/bin"
		main="/usr/share"
fi
}

function git() {
[ -d "${main}/shark" ] && rm -rf ${main}/shark
git clone https://github.com/Bhaviktutorials/shark.git ${main}
}


function Dependicies() {
for i in apache2 php jq tail curl wget; do
    if [ ! -f "${BIN}/${i}" ]; then
    sudo apt-get install ${i} -y 
    fi
    done
}

### INSTALL SCRIPT WGET INSTEAD OF GIT CLONE

function install_ngrok() {
if [ ! -f  "${BIN}/ngrok" ]; then
printf "${white} installing ngrok"
if [ $OS != "TERMUX" ]; then
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
else
wget https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip -O ngrok.zip
fi
unzip ngrok.zip && rm -rf ngrok.zip
fi
}

function setup_ngrok() {
printf "${green} Enter your ngrok authtoken :\n "
read authtoken
$authtoken >> /dev/null 2>&1 && chmod +x ngrok && mv ngrok $BIN
}

function final_touchup() {
for i in shark do;
mv ${main}/shark/${i} ${BIN}
# cp -R shark_logo ${BIN}
printf "${purple} simply run : shark \n ${nc}"
}


#####################################
#       DON'T TRY TO COPY 😂😂     #
#   JUST LEARNING KEEP SUPPORTING   #
#             THANKYOU              #
#####################################
